export const authTypes = {
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  SIGN_UP: "SIGN_UP",
  RESTORE_TOKEN: "RESTORE_TOKEN",
  SHOW_AUTH_ERROR: "SHOW_AUTH_ERROR",
  HIDE_AUTH_ERROR: "HIDE_AUTH_ERROR",
};
